server:
  port: 8080

escassandra:
  local-datacenter: datacenter1
  keyspace: account_reactive_sample
  schema-action: RECREATE # NONE, CREATE, CREATE_IF_NOT_EXISTS, RECREATE, RECREATE_DROP_UNUSED
  contact-points:
    - localhost:9042